name: turbo_waiter
description: Turbo Waiter - Tablet-Optimized Restaurant Management App
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  animated_snack_bar: ^0.4.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  delightful_toast: ^1.1.0
  dio: ^5.9.0
  dropdown_search: ^6.0.2
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_blurhash: ^0.9.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  get_it: ^8.2.0
  http_parser: ^4.1.2
  intl: null
  json_annotation: null
  lottie: ^3.3.2
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0
  retrofit: null
  skeletonizer: ^2.1.0+1

dev_dependencies:
  build_runner: null
  device_preview: ^1.3.1
  flutter_gen_runner: null
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: null
  retrofit_generator: null

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: DIN
      fonts:
        - asset: assets/fonts/DINNextLTArabic-Regular.ttf
    - family: tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf

flutter_assets:
  assets_path: assets/
  output_path: lib/core/helpers
  filename: assets.dart
